local:
  config:
    env: dev

server:
  port: 8883


spring:
  application:
    name: user


  data:
    #数据库
    mongodb:
      uri: mongodb://localhost:27017
      database: "pods"



  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos



#JWT 配置信息
pods:
  jwt:
    header: Authorization
    enabled: true
    secret: XPiPONQyAVv2fcOgOXagY8X0PCNdiMuBjRQpPWcy8fxZEh6Ttty5PwNZ
    user-param-name: userId